import type { LandingContent } from "./types";

export const svSe: LandingContent = {
  locale: "se",
  htmlLang: "sv-SE",
  siteName: "Megatrix",
  market: {
    label: "Sverige",
    flagEmoji: "🇸🇪",
    switchLabel: "🇸🇪 Sverige",
  },
  meta: {
    title: "Lead-to-Job-systemet för värmepumpsinstallatörer | Megatrix",
    description:
      "Megatrix bygger och driver lead-to-job-systemet för värmepumpsinstallatörer: direkt respons, AI-assisterad kvalificering, automatisk uppföljning och full överblick över säljprocessen. Boka en kostnadsfri tillväxtanalys.",
    ogAlt: "Diagram över lead-to-job-processen för värmepumpsinstallatörer",
  },
  announcement: "Vi samarbetar med en värmepumpsinstallatör per serviceområde.",
  nav: {
    links: [
      { label: "Så funkar det", href: "#system" },
      { label: "AI & automation", href: "#ai" },
      { label: "Garanti", href: "#guarantee" },
      { label: "Vanliga frågor", href: "#faq" },
    ],
    ctaLabel: "Boka kostnadsfri analys",
  },
  hero: {
    eyebrow: "Tillväxtsystem för värmepumpsinstallatörer",
    headline: "Fler värmepumpsleads",
    highlight: "blir installerade jobb.",
    subheadline:
      "Megatrix skapar bättre lokal efterfrågan, svarar direkt på varje lead, bokar fler hembesök och följer upp automatiskt — så att färre affärer går förlorade innan de är vunna.",
    primaryCta: { label: "Boka kostnadsfri tillväxtanalys", sublabel: "20 minuter · kostnadsfritt · utan förpliktelser" },
    secondaryCta: { label: "Se hur det fungerar" },
    proofLine:
      "Byggt på samma typ av CRM- och automationsinfrastruktur som moderna installationsföretag använder. Varje AI-åtgärd loggas och granskas av en människa.",
    diagram: {
      stages: ["Ny lead", "Direkt respons", "Kvalificerad", "Hembesök bokat", "Affär vunnen"],
      caption: "Vad som händer automatiskt när en husägare hör av sig",
    },
  },
  credibility: {
    title: "Inte ännu en marknadsföringsbyrå. Ett operativsystem för er säljprocess.",
    items: [
      { title: "Byggt specifikt för värmepumpsbranschen", description: "Varje arbetsflöde är uppbyggt kring hur värmepumpsaffärer faktiskt går till — inte generiska mallar för hantverkare." },
      { title: "AI med mänsklig kontroll", description: "AI skriver utkast, kvalificerar och svarar snabbt. Ert team har alltid kontroll över offert och avslut." },
      { title: "Full spårbarhet", description: "Varje lead spåras från första klick till vunnen affär, så ni vet exakt vilka kanaler som faktiskt lönar sig." },
    ],
  },
  problem: {
    eyebrow: "Problemet",
    title: "Er marknadsföring fungerar. Det är uppföljningen som läcker.",
    intro: "De flesta värmepumpsinstallatörer har inget leadsproblem. De har ett problem med respons och uppföljning — och det kostar affärer varje vecka. Varje obesvarad lead är en värmepump ni inte installerade.",
    items: [
      {
        title: "Färre leads, högre insats",
        description:
          "Konkurrensen om varje förfrågan ökar i takt med att elpriser och stödprogram förändras. De som hör av sig idag är ofta redan intresserade — förlorar ni en av dem till långsam respons kostar det mer än tidigare.",
      },
      {
        title: "Leads kommer in medan montörerna är ute på jobb",
        description: "En husägare ringer eller fyller i ett formulär mitt på dagen. Ingen sitter vid telefonen. Den som ringer tillbaka snabbast får jobbet — och det är sällan ni.",
      },
      {
        title: "Offerter skickas... och glöms bort",
        description: "Ni skickar en bra offert och går vidare till nästa jobb. Inget påminner om uppföljning efter 3 dagar, en vecka eller tre veckor — så ljumna leads kallnar.",
      },
      {
        title: "Leads finns i SMS, röstbrevlådor och Excel-ark",
        description: "Utan en samlad bild av varje leads status försvinner affärer utan att någon märker det förrän kunden redan skrivit på hos någon annan.",
      },
      {
        title: "Ni betalar för leads som aldrig bearbetas",
        description: "Annonsering och leadskällor lönar sig bara om varje lead får snabb och konsekvent uppföljning. Långsam hantering äter tyst upp er kundanskaffningskostnad.",
      },
      {
        title: "Du är flaskhalsen",
        description: "Om tillväxten är beroende av att du personligen kommer ihåg att ringa tillbaka kan verksamheten aldrig växa förbi din egen kalender.",
      },
    ],
  },
  calculator: {
    eyebrow: "Kostnaden för att inte agera",
    title: "Vad kostar långsam uppföljning egentligen?",
    description: "Fyll i era egna siffror nedan. Det här är en förenklad illustration av mekaniken — inte ett branschgenomsnitt eller ett löfte.",
    leadsLabel: "Inkommande leads per månad",
    jobValueLabel: "Genomsnittligt ordervärde",
    estimateRateLabel: "% av leads som leder till offert/hembesök",
    closeRateLabel: "% av offerter som blir affär",
    resultHeadline: "Uppskattad månatlig effekt av 20 % bättre respons och uppföljning",
    lostOpportunitiesLabel: "Uppskattat antal extra affärer / månad",
    lostRevenueLabel: "Uppskattad extra omsättning / månad",
    disclaimer: "Det här är en förenklad illustration baserad på siffrorna ni anger — inte ett löfte, en prognos eller ett branschgenomsnitt. Verkligt utfall beror på er marknad, prissättning och team.",
    ctaText: "Vill ni se hur det ser ut med era riktiga siffror?",
    currencySymbol: "kr",
    currencyPosition: "suffix",
  },
  transformation: {
    eyebrow: "Före / Efter",
    title: "Från läckande leads till en sammanhållen säljprocess",
    intro: "Det här är skillnaden mellan att hoppas att teamet kommer ihåg att följa upp, och att veta att systemet gör det.",
    beforeLabel: "Utan system",
    afterLabel: "Med Lead-to-Job-systemet",
    items: [
      { before: "Lead kommer in, ingen svarar på timmar", after: "Automatiskt svar direkt, dygnet runt" },
      { before: "Manuell och ojämn uppföljning", after: "Schemalagda, automatiska uppföljningssekvenser" },
      { before: "Leads sprids i SMS, mejl och Excel", after: "Alla leads synliga i en samlad pipeline" },
      { before: "Offerter skickas och glöms bort", after: "Offerter följs upp automatiskt tills de vinns eller stängs" },
      { before: "Ingen överblick över vad som fungerar", after: "Tydlig rapportering per leadskälla, svarstid och avslutsfrekvens" },
      { before: "Ägaren är uppföljningssystemet", after: "Systemet fungerar oavsett om du sitter vid skrivbordet eller inte" },
    ],
  },
  system: {
    eyebrow: "Systemet",
    title: "Så fungerar Lead-to-Job-systemet",
    intro: "Åtta komponenter. Ett sammanhängande system, byggt kring hur värmepumpsaffärer faktiskt går till.",
    steps: [
      { index: "01", title: "Generera", description: "Vi hjälper er avgöra rätt mix av Google, Meta och befintliga kanaler för er marknad — inte alla kanaler per automatik." },
      { index: "02", title: "Fånga upp", description: "Samtal, formulär, SMS och missade samtal samlas i ett system istället för att spridas mellan olika inkorgar." },
      { index: "03", title: "Svara", description: "Varje ny lead får ett omedelbart automatiskt svar inom sekunder — så ni aldrig är den installatör som ringde tillbaka för sent." },
      { index: "04", title: "Kvalificera", description: "AI-assisterad kvalificering ställer rätt frågor så ert team lägger tid på riktiga affärsmöjligheter, inte nyfikna." },
      { index: "05", title: "Boka", description: "Bokning sker automatiskt, med bekräftelser och påminnelser som minskar uteblivna besök." },
      { index: "06", title: "Följ upp", description: "Schemalagda uppföljningssekvenser håller er offert top-of-mind tills husägaren bestämt sig — utan att någon behöver komma ihåg det." },
      { index: "07", title: "Konvertera", description: "Varje leads status syns i en gemensam pipeline, så inget faller mellan stolarna och coachning baseras på verklig data." },
      { index: "08", title: "Förbättra", description: "Månadsrapporter om leadskälla, svarstid och konvertering visar vad som fungerar och vad som behöver justeras." },
    ],
  },
  ai: {
    eyebrow: "AI, använt ärligt",
    title: "AI sköter det repetitiva. Ert team fattar besluten som betyder något.",
    intro: "Vi marknadsför inte AI som magi, och vi använder det inte för att ersätta er säljkår. Det finns där för att säkerställa att inget faller mellan stolarna.",
    disclaimer: "Varje AI-assisterat meddelande är synligt för ert team och kan granskas, redigeras eller tas över när som helst.",
    legendAi: "AI hanterar",
    legendHuman: "Alltid en människa",
    legendShared: "AI-assisterat, mänskligt granskat",
    capabilities: [
      { title: "Direkt respons på leads", description: "Bekräftar varje ny lead inom sekunder, i er verksamhets tonalitet.", controlled: "ai" },
      { title: "SMS vid missat samtal", description: "Skickar automatiskt SMS till den ni missat samtal från, innan de ringer en konkurrent.", controlled: "ai" },
      { title: "Kvalificering av leads", description: "Ställer grundläggande frågor (bostadstyp, ålder på nuvarande system, tidsram) innan en människa kopplas in.", controlled: "shared" },
      { title: "Bokning av hembesök", description: "Föreslår lediga tider och bokar bekräftade besök direkt i er kalender.", controlled: "ai" },
      { title: "Svar på vanliga frågor", description: "Besvarar vanliga frågor om finansiering, serviceområde och tidsramar utifrån information ni godkänt.", controlled: "ai" },
      { title: "Offertuppföljning", description: "Skickar schemalagd uppföljning på öppna offerter — ert team avgör när ni ska kliva in personligen.", controlled: "shared" },
      { title: "Prissättning, förhandling och avslut", description: "Sköts alltid av ert team. AI förhandlar aldrig pris och stänger aldrig en affär.", controlled: "human" },
      { title: "Interna notiser", description: "Flaggar heta leads och stillastående offerter till ert team i realtid.", controlled: "ai" },
    ],
  },
  automation: {
    eyebrow: "Automation",
    title: "Det som förut krävde att någon kom ihåg sköter sig nu själv",
    intro: "Stegen är desamma. Det som ändras är om de beror på att en person kommer ihåg att göra dem.",
    manualTitle: "Manuellt",
    manualSteps: [
      "Lead kommer in",
      "En anställd råkar upptäcka den",
      "Anställd svarar, när hen hinner",
      "Anställd kvalificerar leaden manuellt",
      "Anställd kommer ihåg att följa upp (ibland)",
      "Anställd kommer ihåg att boka hembesök",
      "Offertuppföljning beror på att någon minns",
    ],
    automatedTitle: "Med systemet",
    automatedSteps: [
      "Lead kommer in",
      "Automatiskt svar direkt",
      "AI-assisterad kvalificering",
      "Hembesök bokas med påminnelser",
      "Schemalagd uppföljning startar",
      "Pipeline uppdateras automatiskt",
      "Teamet notifieras bara vid behov av mänskligt beslut",
    ],
  },
  channels: {
    eyebrow: "Leadsgenerering",
    title: "Rätt kanaler för er marknad — inte alla kanaler per automatik",
    intro: "Alla värmepumpsinstallatörer behöver inte samma kanaler. Så här ser vi på de två betalda alternativen.",
    cards: [
      { title: "Google Ads & lokal sökannonsering", description: "Fångar husägare som aktivt söker efter värmepumpsinstallation eller byte i ert serviceområde.", bestFor: "Köpredo efterfrågan med hög avsikt" },
      { title: "Meta-annonsering", description: "Bygger medvetenhet och fångar efterfrågan hos husägare som ännu inte börjat söka aktivt — användbart för säsongserbjudanden och finansieringskampanjer.", bestFor: "Medvetenhet och volym i mindre konkurrensutsatta marknader" },
      { title: "Era befintliga kanaler", description: "Referenser, tidigare kunder och nuvarande leadskällor vävs in i samma system så att inget hanteras separat.", bestFor: "Verksamheter med befintligt leadsflöde som behöver bättre hantering" },
    ],
    note: "Rätt mix beror på er marknad, konkurrens och budget. Det avgör vi under analysen — vi placerar inte alla kunder i samma kanaler per automatik.",
  },
  whoFor: {
    title: "Det här är byggt för värmepumpsinstallatörer som:",
    items: [
      { text: "Redan är en etablerad verksamhet med fungerande installationer" },
      { text: "Har kapacitet i teamet för fler jobb" },
      { text: "Får förfrågningar men har svårt att svara på och följa upp alla" },
      { text: "Vill ha mindre manuellt admin, inte ännu ett system att sköta" },
      { text: "Vill ha en upprepningsbar, spårbar säljprocess istället för att lita på minnet" },
    ],
  },
  whoNotFor: {
    title: "Det här passar troligen inte om ni:",
    items: [
      { text: "Är ett helt nystartat företag utan track record eller installationskapacitet ännu" },
      { text: "Inte kan ta er an fler jobb just nu" },
      { text: "Inte är villiga att låta leads kontaktas snabbt, vare sig av ert team eller ett assisterat system" },
      { text: "Letar efter billigast möjliga annonsering, inte en säljprocess" },
      { text: "Saknar ett definierat serviceområde eller nödvändig certifiering och F-skatt för att verka i det" },
    ],
  },
  proof: {
    eyebrow: "Bevis",
    title: "Vi visar hellre mekaniken än hittar på resultat",
    intro:
      "Vi är tidigt i vårt samarbete med värmepumpsinstallatörer, och vi kommer inte att hitta på omdömen, loggor eller siffror för att verka mer etablerade än vi är. Här är vad vi ärligt kan visa er just nu:",
    placeholderTitle: "[Verifierade kundomdömen — kommer snart]",
    placeholderBody: "Allt eftersom vi slutför installationspartnerskap publiceras riktiga omdömen med namn, företag och mätbara resultat här. Fråga oss om aktuella referenser under er analys.",
    caseStudyPlaceholderTitle: "[Verifierad case study — kommer snart]",
    caseStudyPlaceholderBody: "Fullständiga case studies — problem, system, implementation, resultat — publiceras här när de är klara och godkända av kunden.",
  },
  guarantee: {
    eyebrow: "Garanti",
    title: "En garanti baserad på det vi faktiskt kan kontrollera",
    intro: "Vi lovar inte ett antal leads, affärer eller en omsättningsökning — ingen kan ärligt garantera det, och vi tänker inte låtsas att vi kan. Det här garanterar vi:",
    pillars: [
      { title: "Leveransgaranti", description: "Ert system är fullt byggt, testat och i drift inom den överenskomna tidsramen — annars slopas den månadens avgift." },
      { title: "Svarstidsgaranti", description: "Varje lead som kommer in i ert system får ett automatiskt förstasvar inom 60 sekunder, dygnet runt. Sker inte det åtgärdar vi det utan kostnad." },
      { title: "Full transparens", description: "Ni får se varje automation, varje AI-konversation och varje rapport vi bygger — inget är en svart låda." },
    ],
    disclaimer: "Fullständiga garantivillkor bekräftas skriftligt innan ni skriver på något. Garantivillkor är föremål för slutlig juridisk granskning.",
  },
  offer: {
    eyebrow: "Erbjudandet",
    title: "Ett system. Byggt och driftat åt er.",
    intro: "Priset beror på er marknad, nuvarande setup och vilka kanaler som behövs — det bekräftas under er analys, inte på en webbsida. Här är vad som ingår.",
    components: [
      { name: "Grund", summary: "Infrastrukturen allt annat bygger på.", includes: ["CRM och pipeline-uppsättning", "Samtals- och leadsspårning", "Konverterande landningssidor", "Genomgång av er nuvarande webbplats"] },
      { name: "Leadsmotor", summary: "Skapar kvalificerad lokal efterfrågan.", includes: ["Google Ads / lokal sökannonsering (där det passar)", "Meta-annonsering (där det passar)", "Formulär för leadsinsamling", "Rekommenderad kanalmix för er marknad"] },
      { name: "Konverteringsmotor", summary: "Omvandlar förfrågningar till bokade hembesök.", includes: ["Direkt respons på leads", "AI-assisterad kvalificering", "SMS vid missat samtal", "Automatisk bokning av hembesök"] },
      { name: "Säljuppföljning", summary: "Håller offerter och prospekt vid liv.", includes: ["Automatisk offertuppföljning", "Nurture-sekvenser", "Återaktivering av tidigare kunder", "Förfrågan om recensioner och rekommendationer"] },
      { name: "Rapportering & optimering", summary: "Att veta vad som faktiskt fungerar.", includes: ["Månadsrapportering", "Attribution per leadskälla", "Löpande testning och förbättring"] },
    ],
    pricingNote: "Ingen publicerad prislista — det här är ett byggt system, inte ett standardpaket. Ni får en konkret siffra efter analysen, baserat på er marknad och omfattning.",
  },
  mission: {
    eyebrow: "Varför vi byggde det här",
    title: "Värmepumpar är en av de bästa produkterna att sälja inom hantverksbranschen just nu. Många installatörer tappar ändå affären efter att kunden redan tackat ja till ett hembesök.",
    paragraphs: [
      "Efterfrågan på värmepumpar växer — drivet av ett stort utbytesbehov i det befintliga beståndet, höga elpriser och en fortsatt övergång bort från olja och gammal direktverkande el. Men mer efterfrågan betyder inte automatiskt fler installationer. Det betyder mer konkurrens om samma husägares uppmärksamhet.",
      "Vi byggde det här systemet för att de företag som vinner på den här marknaden sällan är de med störst annonsbudget. Det är de som svarar först, följer upp konsekvent och aldrig låter en offert kallna.",
      "[Grundarens bakgrund och företagets historia — läggs till när det finns tillgängligt.]",
    ],
  },
  faq: {
    eyebrow: "Vanliga frågor",
    title: "Frågor innan ni bokar",
    groups: [
      {
        title: "Kom igång",
        items: [
          { q: "Vem är det här för?", a: "Etablerade värmepumpsinstallatörer som redan får inkommande leads men har svårt att svara på och följa upp alla konsekvent. Se avsnittet \"det här är byggt för\" ovan för detaljer." },
          { q: "Genererar ni leads, eller hanterar ni bara de vi redan har?", a: "Båda delarna, beroende på vad ni behöver. Vissa installatörer behöver fler leads; andra får redan tillräckligt men tappar för många på grund av långsam uppföljning. Vi bedömer vad som stämmer för er innan vi rekommenderar något." },
          { q: "Hur snabbt kan vi komma igång?", a: "Merparten av grundsystemet — CRM, direkt respons, bokning — kan vara i drift inom några veckor efter uppstart. Betald annonsering, om det ingår, tar vanligtvis längre tid att komma upp i fart eftersom vi testar vad som fungerar på er marknad." },
          { q: "Vilka marknader jobbar ni med?", a: "Vi arbetar just nu med installatörer i Sverige och USA. Vi stödjer även kommersiella installatörer och flerbostadshus." },
        ],
      },
      {
        title: "Så fungerar systemet",
        items: [
          { q: "Vad implementerar ni exakt?", a: "En CRM och pipeline, insamling och spårning av leads, direkt respons och AI-assisterad kvalificering, automatisk bokning och offertuppföljning — se avsnittet Erbjudandet ovan för hela genomgången." },
          { q: "Använder ni GoHighLevel?", a: "Ja, GoHighLevel är en del av infrastrukturen vi bygger på. Ni behöver varken kunna eller bry er om plattformen — vi sköter den. Ert team möter ett enkelt och begripligt system." },
          { q: "Kan ni jobba med vårt befintliga CRM?", a: "I de flesta fall bygger vi CRM och pipeline som en del av systemet, eftersom mycket av värdet kommer från att respons- och uppföljningsautomation ligger samlat. Är ni djupt investerade i ett befintligt system utvärderar vi ärligt om vi ska bygga runt det eller ersätta det." },
          { q: "Spelar det någon roll om vi jobbar med villa, kommersiellt, luft-luft eller luft-vatten?", a: "Mekaniken i systemet är densamma. Meddelanden, kvalificeringsfrågor och säljcykeln vi automatiserar anpassas efter er specifika mix av tjänster." },
        ],
      },
      {
        title: "AI & automation",
        items: [
          { q: "Kommer AI ersätta min personal?", a: "Nej. AI sköter repetitiva, tidskritiska uppgifter som förstasvar och grundläggande kvalificering. Prissättning, förhandling och avslut ligger alltid hos ert team." },
          { q: "Kommer AI prata med mina kunder?", a: "Vid första kontakt, kvalificering och bokning — ja, och vi är transparenta mot husägare om det. Varje konversation är synlig för ert team och kan tas över när som helst." },
          { q: "Vad händer om AI:n gör fel?", a: "Varje automatiskt meddelande går att granska, och arbetsflödena är byggda för att lämna över till en människa så fort en konversation hamnar utanför det AI bör hantera." },
        ],
      },
      {
        title: "Att jobba tillsammans",
        items: [
          { q: "Vi har redan ett CRM eller en marknadsföringsbyrå — varför byta?", a: "Ni behöver inte byta något för att prata med oss. Under analysen berättar vi ärligt om er nuvarande lösning redan täcker det som betyder något, eller var den läcker." },
          { q: "Vi har provat Google- eller Facebook-annonser utan resultat.", a: "Annonsering utan ett snabbt och konsekvent uppföljningssystem bakom underpresterar ofta — läckan sitter oftast efter annonsen, inte i den. Vi tittar på hela tratten, inte bara trafiken." },
          { q: "Vi har inte tid att implementera det här.", a: "Det är hela poängen med systemet — implementation och daglig drift ligger på oss. Er tidsinsats handlar främst om uppstartssamtalet och löpande beslut som bara ni kan fatta, som prissättning, avslut och serviceområde." },
          { q: "Vad behöver vårt team bidra med?", a: "Tillgång till era nuvarande leadskällor och kalender, grundläggande information om era tjänster och prissättning, samt en kontaktperson för uppstarten. Vi sköter byggandet." },
        ],
      },
      {
        title: "Garanti & pris",
        items: [
          { q: "Hjälper ni oss kommunicera ROT-avdraget till kunder?", a: "Ja. Som av 2026 ligger ROT-avdraget på 30 % av arbetskostnaden, med ett takbelopp på 50 000 kr per person och år (kombinerat med RUT max 75 000 kr). Vi ser till att ert system kommunicerar det korrekt och konsekvent till husägare. Vi ger ingen skatterådgivning — stäm alltid av exakta belopp och villkor med Skatteverket." },
          { q: "Vad kostar det?", a: "Det beror på er marknad, nuvarande setup och vilka komponenter ni behöver. Ni får en konkret siffra efter analysen, inte ett generiskt publicerat pris." },
          { q: "Finns det bindningstid?", a: "Villkoren bekräftas innan ni skriver på något — fråga direkt under er analys." },
          { q: "Vad händer om vi inte får resultat?", a: "Se vårt garantiavsnitt ovan — vi garanterar det vi faktiskt kan kontrollera: leveranstid och svarstid. Vi lovar inte ett specifikt antal affärer, eftersom ingen ärlig byrå kan garantera en husägares beteende." },
          { q: "Vi får redan tillräckligt med rekommendationer.", a: "Bra — rekommendationer är er leadskälla med högst marginal. Systemet gäller även rekommendationsleads: de behöver också direkt respons och konsekvent uppföljning, annars går de till den installatör som följer upp snabbast." },
        ],
      },
    ],
  },
  finalCta: {
    title: "Er nästa lead borde inte bli ännu en missad affär.",
    description: "Låt oss titta på var er nuvarande process läcker installationer — och hur ett lead-to-job-system skulle se ut för er verksamhet.",
    primaryCta: { label: "Boka kostnadsfri tillväxtanalys", sublabel: "20 minuter · kostnadsfritt · utan förpliktelser" },
    secondaryNote: "Vi ställer några frågor om er verksamhet, går igenom er nuvarande leadsprocess och visar konkret var ni tappar affärer.",
  },
  form: {
    eyebrow: "Kostnadsfri tillväxtanalys",
    title: "Se var er leadsprocess läcker",
    description: "Berätta om er verksamhet. Vi återkommer för att boka in er kostnadsfria analys — utan förpliktelser, utan spam.",
    nameLabel: "Namn",
    emailLabel: "E-post",
    phoneLabel: "Telefon",
    companyLabel: "Företagsnamn",
    locationLabel: "Serviceområde (stad/region)",
    locationPlaceholder: "t.ex. Stockholm",
    segmentLabel: "Jobbar ni med privatkunder eller kommersiella kunder?",
    segmentResidential: "Privatkunder",
    segmentCommercial: "Kommersiellt / flerbostadshus",
    heatPumpTypeLabel: "Vilka typer av värmepumpar installerar ni?",
    heatPumpTypeOptions: ["Luft-luft", "Luft-vatten", "Båda", "Annat"],
    volumeLabel: "Ungefärligt antal inkommande leads per månad",
    volumeOptions: ["Under 20", "20–50", "50–100", "100+", "Vet ej"],
    challengeLabel: "Vad är den största utmaningen i er nuvarande process?",
    challengePlaceholder: "t.ex. Vi är långsamma att svara, offerter kallnar, ingen överblick över leads...",
    websiteLabel: "Webbplats (valfritt)",
    submitLabel: "Boka kostnadsfri tillväxtanalys",
    submittingLabel: "Skickar...",
    privacyNote: "Vi säljer aldrig er information.",
    errorRequired: "Det här fältet är obligatoriskt.",
    errorEmail: "Ange en giltig e-postadress.",
    errorPhone: "Ange ett giltigt telefonnummer.",
    genericError: "Något gick fel. Försök igen eller mejla oss direkt.",
  },
  thankYou: {
    eyebrow: "Klart",
    title: "Er förfrågan om analys är mottagen.",
    description: "Så här går det till härnäst.",
    steps: [
      { title: "Vi går igenom er verksamhet", description: "Vi tittar på era nuvarande leadskällor, serviceområde och volym innan vi pratar." },
      { title: "Vi bokar in ett 20-minuters samtal", description: "Ni får inom kort ett mejl och SMS för att välja en tid som passar." },
      { title: "Vi visar var läckan finns", description: "Ni lämnar samtalet med konkret kunskap om var leads faller bort — oavsett om vi jobbar ihop eller inte." },
    ],
    calendarPrompt: "Vill ni boka en tid direkt istället för att vänta på vårt mejl?",
    calendarCtaLabel: "Boka min tid",
    calendarHeading: "Välj en tid som passar er",
    calendarIntro: "20 minuter, helt kostnadsfritt. Välj en ledig tid nedan så bekräftas den direkt — utan mejlpingpong.",
    popupTitle: "Ni är bokade!",
    popupBody: "Er tillväxtanalys är bekräftad. Vi har skickat detaljerna till er e-post — vi ses då.",
    popupCloseLabel: "Uppfattat",
    backHref: "/se",
    backLabel: "Till startsidan",
  },
  footer: {
    tagline: "Lead-to-job-systemet för villainstallatörer av värmepumpar.",
    systemLabel: "Systemet",
    systemLinks: [
      { label: "Så funkar det", href: "#system" },
      { label: "AI & automation", href: "#ai" },
      { label: "Erbjudandet", href: "#offer" },
      { label: "Vanliga frågor", href: "#faq" },
    ],
    marketsLabel: "Marknader",
    companyLabel: "Företag",
    companyLinks: [{ label: "Boka kostnadsfri analys", href: "#lead-form" }],
    legalLinks: [
      { label: "Integritetspolicy", href: "/se/privacy" },
      { label: "Användarvillkor", href: "/se/terms" },
    ],
    disclaimer: "Megatrix är en oberoende tillväxt- och automationspartner för värmepumpsinstallatörer. Vi är inte anslutna till GoHighLevel®, Google eller Meta. Resultat varierar mellan verksamheter och garanteras inte.",
  },
  sticky: {
    ctaLabel: "Boka kostnadsfri analys",
  },
  legal: {
    privacyTitle: "Integritetspolicy",
    privacyBody: [
      "Den här integritetspolicyn förklarar hur Megatrix (\"vi\") samlar in och använder information som skickas in via den här webbplatsen.",
      "Vi samlar in uppgifter ni själva lämnar via våra kontakt- och analysformulär, till exempel namn, e-post, telefonnummer, företag och information om er verksamhet. Uppgifterna används enbart för att besvara er förfrågan, boka in er analys och ge relevant information om våra tjänster.",
      "Vi säljer aldrig era personuppgifter. Vi kan använda cookies och analysverktyg, till exempel Google Analytics och Meta Pixel, för att förstå hur besökare använder webbplatsen och för att mäta annonsering.",
      "Enligt GDPR har ni rätt att begära tillgång till, rättelse av eller radering av era uppgifter. Kontakta oss för att utöva era rättigheter.",
      "Den här sidan är en preliminär text och har ännu inte granskats juridiskt. Den bör granskas och färdigställas i enlighet med GDPR innan webbplatsen samlar in riktiga användaruppgifter i skarp drift.",
    ],
    termsTitle: "Användarvillkor",
    termsBody: [
      "De här användarvillkoren gäller för er användning av den här webbplatsen, som drivs av Megatrix.",
      "Innehållet på sidan är av allmän informativ karaktär och utgör inte en garanti för resultat. Specifika åtaganden — garantier, pris, omfattning — blir bindande först när de bekräftats i ett undertecknat avtal.",
      "Genom att skicka in ett formulär på sidan samtycker ni till att bli kontaktade av vårt team gällande er förfrågan.",
      "Den här sidan är en preliminär text och har ännu inte granskats juridiskt. Den bör färdigställas innan lansering.",
    ],
  },
};
